# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginDialog(object):
    def setupUi(self, loginDialog):
        loginDialog.setObjectName("loginDialog")
        loginDialog.resize(426, 336)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/mysql.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loginDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(loginDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(loginDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtServerAddr = QtWidgets.QLineEdit(loginDialog)
        self.txtServerAddr.setObjectName("txtServerAddr")
        self.gridLayout.addWidget(self.txtServerAddr, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(loginDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtDbName = QtWidgets.QLineEdit(loginDialog)
        self.txtDbName.setObjectName("txtDbName")
        self.gridLayout.addWidget(self.txtDbName, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(loginDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtUserName = QtWidgets.QLineEdit(loginDialog)
        self.txtUserName.setObjectName("txtUserName")
        self.gridLayout.addWidget(self.txtUserName, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(loginDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(loginDialog)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setPlaceholderText("")
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout.addWidget(self.txtPassword, 3, 1, 1, 1)
        self.btnLogin = QtWidgets.QPushButton(loginDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnLogin.setFont(font)
        self.btnLogin.setIconSize(QtCore.QSize(200, 50))
        self.btnLogin.setObjectName("btnLogin")
        self.gridLayout.addWidget(self.btnLogin, 4, 1, 1, 1)

        self.retranslateUi(loginDialog)
        QtCore.QMetaObject.connectSlotsByName(loginDialog)

    def retranslateUi(self, loginDialog):
        _translate = QtCore.QCoreApplication.translate
        loginDialog.setWindowTitle(_translate("loginDialog", "登录"))
        self.label.setText(_translate("loginDialog", "数据库地址"))
        self.txtServerAddr.setText(_translate("loginDialog", "127.0.0.1"))
        self.txtServerAddr.setPlaceholderText(_translate("loginDialog", "127.0.0.1"))
        self.label_2.setText(_translate("loginDialog", "数据库名称"))
        self.txtDbName.setText(_translate("loginDialog", "lab3"))
        self.txtDbName.setPlaceholderText(_translate("loginDialog", "lab3"))
        self.label_3.setText(_translate("loginDialog", "用户名"))
        self.txtUserName.setText(_translate("loginDialog", "root"))
        self.txtUserName.setPlaceholderText(_translate("loginDialog", "root"))
        self.label_4.setText(_translate("loginDialog", "密码"))
        self.txtPassword.setText(_translate("loginDialog", "Wz20020518"))
        self.btnLogin.setText(_translate("loginDialog", "登录"))
import res_rc
