# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/searchRes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchRes(object):
    def setupUi(self, searchRes):
        searchRes.setObjectName("searchRes")
        searchRes.resize(1242, 477)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/mysql.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        searchRes.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(searchRes)
        self.gridLayout.setObjectName("gridLayout")
        self.tbInfo = QtWidgets.QTableWidget(searchRes)
        self.tbInfo.setObjectName("tbInfo")
        self.tbInfo.setColumnCount(0)
        self.tbInfo.setRowCount(0)
        self.gridLayout.addWidget(self.tbInfo, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(465, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.btnClose = QtWidgets.QPushButton(searchRes)
        self.btnClose.setObjectName("btnClose")
        self.gridLayout.addWidget(self.btnClose, 1, 1, 1, 1)

        self.retranslateUi(searchRes)
        QtCore.QMetaObject.connectSlotsByName(searchRes)

    def retranslateUi(self, searchRes):
        _translate = QtCore.QCoreApplication.translate
        searchRes.setWindowTitle(_translate("searchRes", "全部搜索结果"))
        self.btnClose.setText(_translate("searchRes", "关闭"))
import res_rc
